// <auto-generated />
using JwtAuthSample.Store;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JwtAuthSample.Migrations
{
    [DbContext(typeof(JwtDbContext))]
    [Migration("20190531100737_addsql4")]
    partial class addsql4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JwtAuthSample.Entity.Book", b =>
                {
                    b.Property<string>("Id");

                    b.Property<string>("ISBN");

                    b.HasKey("Id");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("JwtAuthSample.Entity.Category", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50);

                    b.Property<string>("CategoryName")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Categorys");
                });

            modelBuilder.Entity("JwtAuthSample.Entity.Product", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50);

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<double>("Price")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("JwtAuthSample.Entity.Book", b =>
                {
                    b.HasOne("JwtAuthSample.Entity.Product", "product")
                        .WithOne("Book")
                        .HasForeignKey("JwtAuthSample.Entity.Book", "Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JwtAuthSample.Entity.Product", b =>
                {
                    b.HasOne("JwtAuthSample.Entity.Category", "CategoryEntity")
                        .WithMany("ProductList")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
